// Shurangama Mantra text data
// Two romanisation systems: Pinyin and Phonetic (BTTS)
// Chinese to be added at a later stage
// Source: BTTS

export type MantraScript = "pinyin" | "phonetic";

export const mantraPinyin: string[] = [
  "na mo sa dan tuo",
  "su qie duo ye",
  "e la he di",
  "san miao san pu tuo xie",
  "na mo sa dan tuo",
  "fo tuo ju zhi shai ni shan",
  "na mo sa po",
  "bo tuo bo di",
  "sa duo pi bi",
  "na mo sa duo nan",
  "san miao san pu tuo",
  "ju zhi nan",
  "suo she la po jia",
  "seng qie nan",
  "na mo lu ji e luo han duo nan",
  "na mo su lu duo bo nuo nan",
  "na mo suo jie li tuo qie mi nan",
  "na mo lu ji san miao qie duo nan",
  "san miao qie bo la",
  "di bo duo nuo nan",
  "na mo ti po li shai nan",
  "na mo xi tuo ye",
  "pi di ye",
  "tuo la li shai nan",
  "she po nu",
  "jie la he",
  "suo he suo la mo tuo nan",
  "na mo ba la he mo ni",
  "na mo yin tuo la ye",
  "na mo po qie po di",
  "lu tuo la ye",
  "wu mo bo di",
  "suo xi ye ye",
  "na mo po qie po di",
  "nuo la ye",
  "na ye",
  "pan zhe mo he san mu tuo la",
  "na mo xi jie li duo ye",
  "na mo po qie po di",
  "mo he jia la ye",
  "di li bo la na",
  "qie la pi tuo la",
  "bo na jia la ye",
  "e di mu di",
  "shi mo she nuo ni",
  "po xi ni",
  "mo dan li qie na",
  "na mo xi jie li duo ye",
  "na mo po qie po di",
  "duo tuo qie duo ju la ye",
  "na mo bo tou mo ju la ye",
  "na mo ba she la ju la ye",
  "na mo mo ni ju la ye",
  "na mo qie she ju la ye",
  "na mo po qie po di",
  "di li cha",
  "shu la xi na",
  "bo la he la na la she ye",
  "duo tuo qie duo ye",
  "na mo po qie po di",
  "na mo e mi duo po ye",
  "duo tuo qie duo ye",
  "e la he di",
  "san miao san pu tuo ye",
  "na mo po qie po di",
  "e chu pi ye",
  "duo tuo qie duo ye",
  "e la he di",
  "san miao san pu tuo ye",
  "na mo po qie po di",
  "bi sha she ye",
  "ju lu fei zhu li ye",
  "bo la po la she ye",
  "duo tuo qie duo ye",
  "na mo po qie po di",
  "san bu shi bi duo",
  "sa lian nai la la she ye",
  "duo tuo qie duo ye",
  "e la he di",
  "san miao san pu tuo ye",
  "na mo po qie po di",
  "she ji ye mu nuo ye",
  "duo tuo qie duo ye",
  "e la he di",
  "san miao san pu tuo ye",
  "na mo po qie po di",
  "la dan na ji du la she ye",
  "duo tuo qie duo ye",
  "e la he di",
  "san miao san pu tuo ye",
  "di piao",
  "na mo sa jie li duo",
  "yi tan po qie po duo",
  "sa dan tuo qie du shai ni shan",
  "sa dan duo bo da lan",
  "na mo e po la shi dan",
  "bo la di",
  "yang qi la",
  "sa la po",
  "bo duo jie la he",
  "ni jie la he",
  "jie jia la he ni",
  "ba la bi di ye",
  "chi tuo ni",
  "e jia la",
  "mi li zhu",
  "bo li dan la ye",
  "ning jie li",
  "sa la po",
  "pan tuo nuo",
  "mu cha ni",
  "sa la po",
  "tu shai jia",
  "tu xi fa",
  "bo na ni",
  "fa la ni",
  "zhe du la",
  "shi di nan",
  "jie la he",
  "suo he sa la ruo she",
  "pi duo beng suo na jie li",
  "e shai zha bing she di nan",
  "na cha cha dan la ruo she",
  "bo la sa tuo na jie li",
  "e shai zha nan",
  "mo he jie la he ruo she",
  "pi duo beng sa na jie li",
  "sa po she du lu",
  "ni po la ruo she",
  "hu lan tu xi fa",
  "nan zhe na she ni",
  "bi sha she",
  "xi dan la",
  "e ji ni",
  "wu tuo jia la ruo she",
  "e bo la shi duo ju la",
  "mo he bo la zhan chi",
  "mo he die duo",
  "mo he di she",
  "mo he shui duo she po la",
  "mo he ba la pan tuo la",
  "po xi ni",
  "e li ye duo la",
  "pi li ju zhi",
  "shi po pi she ye",
  "ba she la mo li di",
  "pi she lu duo",
  "bo teng wang jia",
  "ba she la zhi he nuo e zhe",
  "mo la zhi po",
  "bo la zhi duo",
  "ba she la shan chi",
  "pi she la zhe",
  "shan duo she",
  "pi ti po",
  "bu shi duo",
  "su mo lu bo",
  "mo he shui duo",
  "e li ye duo la",
  "mo he po la e bo la",
  "ba she la shang jie la zhi po",
  "ba she la ju mo li",
  "ju lan tuo li",
  "ba she la he sa duo zhe",
  "pi di ye",
  "qian zhe nuo",
  "mo li jia",
  "ku su mu",
  "po jie la duo nuo",
  "pi lu zhe na",
  "ju li ye",
  "ye la tu",
  "shai ni shan",
  "pi zhe lan po mo ni zhe",
  "ba she la jia na jia bo la po",
  "lu she na",
  "ba she la dun zhi zhe",
  "shui duo zhe",
  "jia mo la",
  "cha che shi",
  "bo la po",
  "yi di yi di",
  "mu tuo la",
  "jie na",
  "suo pi la chan",
  "jue fan du",
  "yin tu na mo mo xie",
  "wu xin",
  "li shai jie na",
  "bo la she xi duo",
  "sa dan tuo",
  "qie du shai ni shan",
  "hu xin du lu yong",
  "zhan po na",
  "hu xin du lu yong",
  "xi dan po na",
  "hu xin du lu yong",
  "bo la shai di ye",
  "san bo cha",
  "na jie la",
  "hu xin du lu yong",
  "sa po yao cha",
  "he la cha suo",
  "jie la he ruo she",
  "pi teng beng sa na jie la",
  "hu xin du lu yong",
  "zhe du la",
  "shi di nan",
  "jie la he",
  "suo he sa la nan",
  "pi teng beng sa na la",
  "hu xin du lu yong",
  "la cha",
  "po qie fan",
  "sa dan tuo",
  "qie du shai ni shan",
  "bo la dian",
  "she ji li",
  "mo he suo he sa la",
  "bo shu suo he sa la",
  "shi li sha",
  "ju zhi suo he sa ni",
  "di li e bi ti shi po li duo",
  "zha zha ying jia",
  "mo he ba she lu tuo la",
  "di li pu po na",
  "man cha la",
  "wu xin",
  "suo xi di",
  "bo po du",
  "mo mo",
  "yin tu na mo mo xie",
  "la she po ye",
  "zhu la ba ye",
  "e qi ni po ye",
  "wu tuo jia po ye",
  "pi sha po ye",
  "she sa duo la po ye",
  "po la zhao jie la po ye",
  "tu shai cha po ye",
  "e she ni po ye",
  "e jia la",
  "mi li zhu po ye",
  "tuo la ni bu mi jian",
  "bo qie bo tuo po ye",
  "wu la jia po duo po ye",
  "la she tan cha po ye",
  "nuo qie po ye",
  "pi tiao dan po ye",
  "su bo la na po ye",
  "yao cha jie la he",
  "la cha si jie la he",
  "bi li duo jie la he",
  "pi she zhe jie la he",
  "bu duo jie la he",
  "jiu pan cha jie la he",
  "bu dan na jie la he",
  "jia zha bu dan na jie la he",
  "xi qian du jie la he",
  "e bo xi mo la jie la he",
  "wu tan mo tuo jie la he",
  "che ye jie la he",
  "xi li po di jie la he",
  "she duo he li nan",
  "jie po he li nan",
  "lu di la he li nan",
  "mang suo he li nan",
  "mi tuo he li nan",
  "mo she he li nan",
  "she duo he li nu",
  "shi bi duo he li nan",
  "pi duo he li nan",
  "po duo he li nan",
  "e shu zhe he li nu",
  "zhi duo he li nu",
  "di shan sa pi shan",
  "sa po jie la he nan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "bo li ba la zhe jia",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "cha yan ni",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "mo he bo shu bo dan ye",
  "lu tuo la",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "nuo la ye na",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "dan tuo qie lu cha xi",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "mo he jia la",
  "mo dan li qie na",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "jia bo li jia",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "she ye jie la",
  "mo du jie la",
  "sa po la tuo suo da na",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "zhe du la",
  "po qi ni",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "pi li yang qi li zhi",
  "nan tuo ji sha la",
  "qie na bo di",
  "suo xi ye",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "na jie na she la po na",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "e luo han",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "pi duo la qie",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "ba she la bo ni",
  "ju xi ye ju xi ye",
  "jia di bo di",
  "qi li dan",
  "pi tuo ye she",
  "chen tuo ye mi",
  "ji la ye mi",
  "la cha wang",
  "po qie fan",
  "yin tu na mo mo xie",
  "po qie fan",
  "sa dan duo bo da la",
  "na mo cui du di",
  "e xi duo na la la jia",
  "bo la po",
  "xi pu zha",
  "pi jia sa dan duo bo de li",
  "shi fo la shi fo la",
  "tuo la tuo la",
  "pin tuo la pin tuo la",
  "chen tuo chen tuo",
  "hu xin hu xin",
  "pan zha pan zha pan zha pan zha pan zha",
  "suo he",
  "xi xi pan",
  "e mu jia ye pan",
  "e bo la ti he duo pan",
  "po la bo la tuo pan",
  "e su la",
  "pi tuo la",
  "bo jia pan",
  "sa po ti pi bi pan",
  "sa po na qie bi pan",
  "sa po yao cha bi pan",
  "sa po qian ta po bi pan",
  "sa po bu dan na bi pan",
  "jia zha bu dan na bi pan",
  "sa po tu lang zhi di bi pan",
  "sa po tu si bi li",
  "qi shai di bi pan",
  "sa po shi po li bi pan",
  "sa po e bo xi mo li bi pan",
  "sa po she la po na bi pan",
  "sa po di di ji bi pan",
  "sa po dan mo tuo ji bi pan",
  "sa po pi tuo ye",
  "la shi zhe li bi pan",
  "she ye jie la",
  "mo du jie la",
  "sa po la tuo suo tuo ji bi pan",
  "pi di ye",
  "zhe li bi pan",
  "zhe du la",
  "fu qi ni bi pan",
  "ba she la",
  "ju mo li",
  "pi tuo ye",
  "la shi bi pan",
  "mo he bo la ding yang",
  "yi qi li bi pan",
  "ba she la shang jie la ye",
  "bo la zhang qi la she ye pan",
  "mo he jia la ye",
  "mo he mo dan li jia na",
  "na mo suo jie li duo ye pan",
  "bi shai na bei ye pan",
  "bo la he mo ni ye pan",
  "e qi ni ye pan",
  "mo he jie li ye pan",
  "jie la tan chi ye pan",
  "mie dan li ye pan",
  "lao dan li ye pan",
  "zhe wen cha ye pan",
  "jie luo la dan li ye pan",
  "jia bo li ye pan",
  "e di mu zhi duo",
  "jia shi mo she nuo",
  "po si ni ye pan",
  "yan ji zhi",
  "sa tuo po xie",
  "mo mo yin tu na mo mo xie",
  "tu shai zha zhi duo",
  "e mo dan li zhi duo",
  "wu she he la",
  "qie po he la",
  "lu di la he la",
  "po suo he la",
  "mo she he la",
  "she duo he la",
  "shi bi duo he la",
  "ba liao ye he la",
  "qian tuo he la",
  "bu shi bo he la",
  "po la he la",
  "po xie he la",
  "bo bo zhi duo",
  "tu shai zha zhi duo",
  "lao tuo la zhi duo",
  "yao cha jie la he",
  "la cha suo jie la he",
  "bi li duo jie la he",
  "pi she zhe jie la he",
  "bu duo jie la he",
  "jiu pan cha jie la he",
  "xi qian tuo jie la he",
  "wu dan mo tuo jie la he",
  "che ye jie la he",
  "e bo sa mo la jie la he",
  "zhai que ge",
  "cha qi ni jie la he",
  "li fo di jie la he",
  "she mi jia jie la he",
  "she ju ni jie la he",
  "mu tuo la",
  "nan di jia jie la he",
  "e lan po jie la he",
  "qian du bo ni jie la he",
  "shi fa la",
  "yin jia xi jia",
  "zhui di yao jia",
  "dan li di yao jia",
  "zhe tu tuo jia",
  "ni ti shi fa la",
  "bi shan mo shi fa la",
  "bo di jia",
  "bi di jia",
  "shi li shai mi jia",
  "suo ni bo di jia",
  "sa po shi fa la",
  "shi lu ji di",
  "mo tuo pi da lu zhi qian",
  "e qi lu qian",
  "mu que lu qian",
  "jie li tu lu qian",
  "jie la he",
  "jie lan jie na shu lan",
  "dan duo shu lan",
  "qi li ye shu lan",
  "mo mo shu lan",
  "ba li shi po shu lan",
  "bi li shai zha shu lan",
  "wu tuo la shu lan",
  "jie zhi shu lan",
  "ba xi di shu lan",
  "wu lu shu lan",
  "chang qie shu lan",
  "he xi duo shu lan",
  "ba tuo shu lan",
  "suo fang ang qie",
  "bo la zhang qie shu lan",
  "bu duo bi duo cha",
  "cha qi ni",
  "shi po la",
  "tuo tu lu jia",
  "jian du lu ji zhi",
  "po lu duo pi",
  "sa bo lu",
  "he ling qie",
  "shu sha dan la",
  "suo na jie la",
  "pi sha yu jia",
  "e qi ni",
  "wu tuo jia",
  "mo la pi la",
  "jian duo la",
  "e jia la",
  "mi li du",
  "da lian bu jia",
  "di li la zha",
  "bi li shai zhi jia",
  "sa po na ju la",
  "si yin qie bi",
  "jie la li yao cha",
  "dan la chu",
  "mo la shi",
  "fei di shan",
  "suo pi shan",
  "xi dan duo bo da la",
  "mo he ba she lu",
  "shai ni shan",
  "mo he bo lai zhang qi lan",
  "ye bo tu tuo",
  "she yu she nuo",
  "bian da li na",
  "pi tuo ye",
  "pan tan jia lu mi",
  "di shu",
  "pan tan jia lu mi",
  "bo la pi tuo",
  "pan tan jia lu mi",
  "da zhi tuo",
  "nan",
  "e na li",
  "pi she ti",
  "pi la",
  "ba she la",
  "tuo li",
  "pan tuo pan tuo ni",
  "ba she la bang ni pan",
  "hu xin du lu yong pan",
  "suo po he",
];

export const mantraPhonetic: string[] = [
  "na mwo sa dan two",
  "su chye dwo ye",
  "e la he di",
  "san myau san pu two sye",
  "na mwo sa dan two",
  "fwo two jyu jr shai ni shan",
  "na mwo sa pe",
  "bwo two bwo di",
  "sa dwo pi bi",
  "na mwo sa dwo nan",
  "san myau san pu two",
  "jyu jr nan",
  "swo she la pe jya",
  "seng chye nan",
  "na mwo lu ji e lwo han dwo nan",
  "na mwo su lu dwo bwo nwo nan",
  "na mwo swo jye li two chye mi nan",
  "na mwo lu ji san myau chye dwo nan",
  "san myau chye be la",
  "di bwo dwo nwo nan",
  "na mwo ti pe li shai nan",
  "na mwo syi two ye",
  "pi di ye",
  "two la li shai nan",
  "she pwo nu",
  "jye la he",
  "swo he swo la mwo two nan",
  "na mwo ba la he mwo ni",
  "na mwo yin two la ye",
  "na mwo pe chye pe di",
  "lu two la ye",
  "wu mwo bwo di",
  "swo syi ye ye",
  "na mwo pe chye pe di",
  "nwo la ye",
  "na ye",
  "pan je mwo he san mwo two la",
  "na mwo syi jye li dwo ye",
  "na mwo pe chye pe di",
  "mwo he jya la ye",
  "di li bwo la na",
  "chye la pi two la",
  "bwo na jya la ye",
  "e di mu di",
  "shr mwo she nwo ni",
  "pe syi ni",
  "mwo dan li chye na",
  "na mwo syi jye li dwo ye",
  "na mwo pe chye pe di",
  "dwo two chye dwo jyu la ye",
  "na mwo be tou mwo jyu la ye",
  "na mwo ba she la jyu la ye",
  "na mwo mwo ni jyu la ye",
  "na mwo chye she jyu la ye",
  "na mwo pe chye pe di",
  "di li cha",
  "shu la syi na",
  "bwo la he la na la she ye",
  "dwo two chye dwo ye",
  "na mwo pe chye pe di",
  "na mwo e mi dwo pe ye",
  "dwo two chye dwo ye",
  "e la he di",
  "san myau san pu two ye",
  "na mwo pe chye pe di",
  "e chu pi ye",
  "dwo two chye dwo ye",
  "e la he di",
  "san myau san pu two ye",
  "na mwo pe chye pe di",
  "bi sha she ye",
  "jyu lu fei ju li ye",
  "bwo la pe la she ye",
  "dwo two chye dwo ye",
  "na mwo pe chye pe di",
  "san bu shr bi dwo",
  "sa lyan nai la la she ye",
  "dwo two chye dwo ye",
  "e la he di",
  "san myau san pu two ye",
  "na mwo pe chye pe di",
  "she ji ye mu nwo ye",
  "dwo two chye dwo ye",
  "e la he di",
  "san myau san pu two ye",
  "na mwo pe chye pe di",
  "la dan na ji du la she ye",
  "dwo two chye dwo ye",
  "e la he di",
  "san myau san pu two ye",
  "di pyau",
  "na mwo sa jye li dwo",
  "yi tan pe chye pe dwo",
  "sa dan two chye du shai ni shan",
  "sa dan dwo bwo da lan",
  "na mwo e pe la shr dan",
  "bwo la di",
  "yang chi la",
  "sa la pe",
  "bwo dwo jye la he",
  "ni jye la he",
  "jye jya la he ni",
  "ba la bi di ye",
  "chr two ni",
  "e jye la",
  "mi li ju",
  "bwo li dan la ye",
  "ning jye li",
  "sa la pe",
  "pan two nwo",
  "mu cha ni",
  "sa la pe",
  "tu shai ja",
  "tu syi fa",
  "bwo na ni",
  "fa la ni",
  "je du la",
  "shr di nan",
  "jye la he",
  "swo he sa la rau she",
  "pi dwo beng swo na jye li",
  "e shai ja bing she di nan",
  "na cha cha dan la rau she",
  "bwo la sa two na jye li",
  "e shai ja nan",
  "mwo he jye la he rau she",
  "pi dwo beng sa na jye li",
  "sa pe she du lu",
  "ni pe la rau she",
  "hu lan tu syi fa",
  "nan je na she ni",
  "pe sha she",
  "syi dan la",
  "e ji ni",
  "wu two jya la rau she",
  "e bwo la shr dwo jyu la",
  "mwo he bwo la jan chr",
  "mwo he dye dwo",
  "mwo he di she",
  "mwo he shwei dwo she pe la",
  "mwo he ba la pan two la",
  "pe syi ni",
  "e li ye dwo la",
  "pi li jyu jr",
  "shr pe pi she ye",
  "ba she la mwo li di",
  "pi she lu dwo",
  "bwo teng wang jya",
  "ba she la jr he nwo e je",
  "mwo la jr pe",
  "bwo la jr dwo",
  "ba she la shan chr",
  "pi she la je",
  "shan dwo she",
  "pi ti pe",
  "bu shr dwo",
  "su mwo lu bwo",
  "mwo he shwei dwo",
  "e li ye dwo la",
  "mwo he pe la e bwo la",
  "ba she la shang jye la jr pe",
  "ba she la jyu mwo li",
  "jyu lan two li",
  "ba she la he sa dwo je",
  "pi di ye",
  "chyan je nwo",
  "mwo li jya",
  "ku su mu",
  "pe jye la dwo nwo",
  "pi lu je na",
  "jyu li ye",
  "ye la tu",
  "shai ni shan",
  "pi je lan pe. mwo ni je",
  "ba she la jya na jya bwo la pe",
  "lu she na",
  "ba she la dwo jr je",
  "shwei dwo je",
  "jya mwo la",
  "cha che shr",
  "bwo la pe",
  "yi di yi di",
  "mu two la",
  "jye na",
  "swo pi la chan",
  "jywe fan du",
  "yin tu na mwo mwo sye",
  "wu syin",
  "li shai jye na",
  "bwo la she syi dwo",
  "sa dan two",
  "chye du shai ni shan",
  "hu syin du lu yung",
  "jan pe na",
  "hu syin du lu yung",
  "syi dan pe na",
  "hu syin du lu yung",
  "bwo la shai di ye",
  "san bwo cha",
  "na jye la",
  "hu syin du lu yung",
  "sa pe yau cha",
  "he la cha swo",
  "jye la he rau she",
  "pi teng beng sa na jye la",
  "hu syin du lu yung",
  "je du la",
  "shr di nan",
  "jye la he",
  "swo he sa la nan",
  "pi teng beng sa na la",
  "hu syin du lu yung",
  "la cha",
  "pe chye fan",
  "sa dan two",
  "chye du shai ni shan",
  "bwo la dyan",
  "she ji li",
  "mwo he swo he sa la",
  "bwo shu swo he sa la",
  "shr li sha",
  "jyu jr swo he sa ni",
  "di li e bi ti shr pe li dwo",
  "ja ja ying jya",
  "mwo he ba she lu two la",
  "di li pu pe na",
  "man cha la",
  "wu syin",
  "swo syi di",
  "bwo pe du",
  "mwo mwo",
  "yin two na mwo mwo sye",
  "la shr pe ye",
  "ju la ba ye",
  "e chi ni pe ye",
  "wu two jya pe ye",
  "pi sha pe ye",
  "she sa dwo la pe ye",
  "pe la jau jye la pe ye",
  "tu shai cha pe ye",
  "e she ni pe ye",
  "e jya la",
  "mi li ju pe ye",
  "two la ni bu mi jyan",
  "bwo chye bwo two pe ye",
  "wu la jya pe dwo pe ye",
  "la she tan cha pe ye",
  "nwo chye pe ye",
  "pi tyau dan pe ye",
  "su bwo la na pe ye",
  "yau cha jye la he",
  "la cha syi jye la he",
  "bi li dwo jye la he",
  "pi she je jye la he",
  "bu dwo jye la he",
  "jyou pan cha jye la he",
  "bu dan na jye la he",
  "jya ja bu dan na jye la he",
  "syi chan du jye la he",
  "e bwo syi mwo la jye la he",
  "wu tan mwo two jye la he",
  "che ye jye la he",
  "syi li pe di jye la he",
  "she dwo he li nan",
  "jye pe he li nan",
  "lu di la he li nan",
  "mang swo he li nan",
  "mi two he li nan",
  "mwo she he li nan",
  "she dwo he li nyu",
  "shr bi dwo he li nan",
  "pi dwo he li nan",
  "pe dwo he li nan",
  "e shu je he li nyu",
  "jr dwo he li nyu",
  "di shan sa pi shan",
  "sa pe jye la he nan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "bwo li ba la je jya",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "cha yan ni",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "mwo he bwo su bwo dan ye",
  "lu two la",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "nwo la ye na",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "dan two chye lu cha syi",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "mwo he jya la",
  "mwo dan li chye na",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "jya bwo li jya",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "she ye jye la",
  "mwo du jye la",
  "sa pe la two swo da na",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "je du la",
  "pe chi ni",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "pi li yang chi li jr",
  "nan two ji sha la",
  "chye na bwo di",
  "swo syi ye",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "na jye na she la pe na",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "e lwo han",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "pi dwo la chye",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "ba she la bwo ni",
  "jyu syi ye jyu syi ye",
  "jya di bwo di",
  "chi li dan",
  "pi two ye she",
  "chen two ye mi",
  "ji la ye mi",
  "la cha wang",
  "pe chye fan",
  "yin tu na mwo mwo sye",
  "pe chye fan",
  "sa dan dwo bwo da la",
  "na mwo tswei du di",
  "e syi dwo na la la jya",
  "bwo la pe",
  "syi pu ja",
  "pi jya sa dan dwo be di li",
  "shr fwo la shr fwo la",
  "two la two la",
  "pin two la pin two la",
  "chen two chen two",
  "hu syin hu syin",
  "pan ja pan ja pan ja pan ja pan ja",
  "swo he",
  "syi syi pan",
  "e mu jya ye pan",
  "e bwo la ti he dwo pan",
  "pe la bwo la two pan",
  "e su la",
  "pi two la",
  "bwo jya pan",
  "sa pe ti pi bi pan",
  "sa pe na chye bi pan",
  "sa pe yau cha bi pan",
  "sa pe chyan ta pe bi pan",
  "sa pe bu dan na bi pan",
  "jya ja bu dan na bi pan",
  "sa pe tu lang jr di bi pan",
  "sa pe tu syi bi li",
  "chi shai di bi pan",
  "sa pe shr pe li bi pan",
  "sa pe e bwo syi mwo li bi pan",
  "sa pe she la pe na bi pan",
  "sa pe di di ji bi pan",
  "sa pe dan mwo two ji bi pan",
  "sa pe pi two ye",
  "la shr je li bi pan ",
  "she ye jye la",
  "mwo du jye la",
  "sa pe la two swo two ji bi pan",
  "pi di ye",
  "je li bi pan",
  "je du la",
  "fu chi ni bi pan",
  "ba she la",
  "jyu mwo li",
  "pi two ye",
  "la shr bi pan",
  "mwo he bwo la ding yang",
  "yi chi li bi pan",
  "ba she la shang jye la ye",
  "bwo la jang chi la she ye pan",
  "mwo he jya la ye",
  "mwo he mwo dan li jya na",
  "na mwo swo jye li dwo ye pan",
  "bi shai na bei ye pan",
  "bwo la he mwo ni ye pan",
  "e chi ni ye pan",
  "mwo he jye li ye pan",
  "jye la tan chr ye pan",
  "mye dan li ye pan",
  "lau dan li ye pan",
  "je wen cha ye pan",
  "jye lwo la dan li ye pan",
  "jya bwo li ye pan",
  "e di mu jr dwo",
  "jya shr mwo she nwo",
  "pe syi ni ye pan",
  "yan ji jr",
  "sa two pe sye",
  "mwo mwo yin tu na mwo mwo sye",
  "tu shai ja jr dwo",
  "e mwo dan li jr dwo",
  "wu she he la",
  "chye pe he la",
  "lu di la he la",
  "pe swo he la",
  "mwo she he la",
  "she dwo he la",
  "shr bi dwo he la",
  "ba lyau ye he la",
  "chyan two he la",
  "bu shr bwo he la",
  "pwo la he la",
  "pe sye he la",
  "be bwo jr dwo",
  "tu shai ja jr dwo",
  "lau two la jr dwo",
  "yau cha jye la he",
  "la cha swo jye la he",
  "bi li dwo jye la he",
  "pi she je jye la he",
  "bu dwo jye la he",
  "jyou pan cha jye la he",
  "syi chyan two jye la he",
  "wu dan mwo two jye la he",
  "che ye jye la he",
  "e bwo sa mwo la jye la he",
  "jai chywe ge",
  "cha chi ni jye la he",
  "li fwo di jye la he",
  "she mi jya jye la he",
  "she jyu ni jye la he",
  "mu two la",
  "na di jya jye la he",
  "e lan pe jye la he",
  "chyan du bwo ni jye la he",
  "shr fwo la",
  "yin jya syi jya",
  "jwei di yau jya",
  "dan li di yau jya",
  "je tu two jya",
  "ni ti shr fa la",
  "bi shan mwo shr fa la",
  "bwo di jya",
  "bi di jya",
  "shr li shai mi jya",
  "swo ni bwo di jya",
  "sa pe shr fa la",
  "shr lu ji di",
  "mwo two pi da lu jr jyan",
  "e chi lu chyan",
  "mu chywe lu chyan",
  "jye li tu lu chyan",
  "jya la he",
  "jye lan jye na shu lan",
  "dan dwo shu lan",
  "chi li ye shu lan",
  "mwo mwo shu lan",
  "ba li shr pe shu lan",
  "bi li shai ja shu lan",
  "wu two la shu lan",
  "jye jr shu lan",
  "ba syi di shu lan",
  "wu lu shu lan",
  "chang chye shu lan",
  "he syi dwo shu lan",
  "ba two shu lan",
  "swo fang ang chye",
  "bwo la jang chye shu lan",
  "bu dwo bi dwo cha",
  "cha chi ni",
  "shr pe la",
  "two tu lu jya",
  "jyan du lu ji jr",
  "pe lu dwo pi",
  "sa bwo lu",
  "he ling chye",
  "shu sha dan la",
  "swo na jye la",
  "pi sha yu jya",
  "e chi ni",
  "wu two jya",
  "mwo la pi la",
  "jyan dwo la",
  "e jya la",
  "mi li du",
  "da lyan bu jya",
  "di li la ja",
  "bi li shai jr jya",
  "sa pe na jyu la",
  "si yin chye bi",
  "jye la li yau cha",
  "dan la chu",
  "mwo la shr",
  "fei di shan",
  "swo pi shan",
  "syi dan dwo bwo da la",
  "mwo he ba she lu",
  "shai ni shan",
  "mwo he bwo lai jang chi lan",
  "ye bwo tu two",
  "she yu she nwo",
  "byan da li na",
  "pi two ye",
  "pan tan jya lu mi",
  "di shu",
  "pan tan jya lu mi",
  "bwo la pi two",
  "pan tan jya lu mi",
  "da jr two",
  "nan",
  "e na li",
  "pi she ti",
  "pi la",
  "ba she la",
  "two li",
  "pan two pan two ni",
  "ba she la bang ni pan",
  "hu syin du lu yung pan",
  "swo pe he",
];

export const mantraLines: Record<MantraScript, string[]> = {
  pinyin: mantraPinyin,
  phonetic: mantraPhonetic,
};
